set nocompatible
filetype off
au BufEnter /private/tmp/crontab.* setl backupcopy=yes
" let g:do_filetype = 0
" au BufWinEnter,BufAdd * if expand('<afile>') == "" | let g:do_filetype = 1 | endif
set rtp+=~/.vim/bundle/Vundle.vim
set rtp+=~/Code/projects/vim/vim-mpc
runtime! init/**.vim
call vundle#begin()

"global
  Plugin 'gmarik/Vundle.vim'
  Plugin 'airblade/vim-gitgutter'
  Plugin 'benmills/vimux'
  Plugin 'kien/ctrlp.vim'
  Plugin 'tpope/vim-rsi'
  Plugin 'tpope/vim-projectionist'
  Plugin 'richsoni/vim-ecliptic'
  " Writing
  Plugin 'git@github.com:reedes/vim-lexical.git'
  Plugin 'townk/vim-autoclose'
  Plugin 'richsoni/vim-2dotxt'
  Plugin 'ticketevolution/ticketevo.vim'
  Plugin 'richsoni/vim-capmap'
  Plugin 'tpope/vim-dispatch'
  Plugin 'felixge/vim-nodejs-errorformat'
  Plugin 'tpope/vim-vinegar'
  Plugin 'tpope/vim-eunuch'
  Plugin 'tpope/vim-scriptease'
  Plugin 'tpope/vim-fugitive'
  Plugin 'tpope/vim-sensible'
  Plugin 'tpope/vim-unimpaired'
  Plugin 'tommcdo/vim-exchange'
  Plugin 'SirVer/ultisnips'
"editing
  Plugin 'godlygeek/tabular'
  Plugin 'AndrewRadev/splitjoin.vim'
  Plugin 'tpope/vim-abolish'
  Plugin 'tpope/vim-commentary'
  Plugin 'tpope/vim-endwise'
  Plugin 'tpope/vim-ragtag'
  Plugin 'tpope/vim-repeat'
  Plugin 'tpope/vim-surround'
  Plugin 'tpope/vim-speeddating'
"languages
  Plugin 'jussi-kalliokoski/harmony.vim'
  Plugin 'tpope/vim-coffee-script'
  Plugin 'moll/vim-node'
  Plugin 'tpope/vim-haml'
  Plugin 'tpope/vim-markdown'
  Plugin 'tpope/vim-rails'
  Plugin 'vim-ruby/vim-ruby'
  Plugin 'mtscout6/vim-cjsx.git'
  Plugin 'dagwieers/asciidoc-vim'
"colors
  Plugin 'vim-scripts/tir_black'
  Plugin 'twerth/ir_black'

call vundle#end()

filetype plugin indent on
set background=dark
colorscheme grb256
" autocmd BufEnter,BufNewFile,BufRead * if &filetype == "" | setlocal ft=2dotxt | endif
" autocmd BufEnter,BufNewFile,BufRead * if &filetype == "" | setf 2dotxt | endif
" autocmd BufEnter,BufNewFile,BufRead * syntax on
