source ~/.local_profile
source ~/.profile
export ZSH=$HOME/.oh-my-zsh
unsetopt share_history
setopt no_share_history
plugins=(git yarn)

source $ZSH/oh-my-zsh.sh
source $CONFIG_PATH/zsh/prompt.zsh
source $CONFIG_PATH/sh/aliases.sh
bindkey -e
precmd() {
  underline_prompt
}


export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
