echo "~/.zshrc"
source ~/.profile
export ZSH=$HOME/.oh-my-zsh
unsetopt share_history
setopt no_share_history
plugins=(git)

source $ZSH/oh-my-zsh.sh
source ~/richsoni-config/bash/prompt.sh
source ~/richsoni-config/sh/aliases.sh
bindkey -e
precmd() {
  underline_prompt
}

# export NVM_DIR="/Users/rsoni/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
source $HOME/.rvm/scripts/rvm
  export NVM_DIR="$HOME/.nvm"
  . "/usr/local/opt/nvm/nvm.sh"
source /Users/rsoni/.we/werc
