#!/usr/bin/env ruby
######METHODS######
  def death_by_usage
    puts 'Quiz -- Usage:'
    puts '  quiz ask {existing_file}  quiz you no the least known word'
    puts '  file format answer | question | (I add the score for you here)'
    exit
  end

  def ignore(line)
    comment = line[0] == '#'
    blank   = (line =~ /^\s+$/)
    comment || blank
  end

  class Line
    attr_accessor :line_number, :question, :answer, :num_asked, :num_right, :src, :filename

    def initialize(line_src, filename, line_number)
      line = Line.format line_src
      self.question    = line[0]
      self.answer      = line[1]
      self.num_asked   = line[2] if line.length > 2
      self.num_right   = line[3] if line.length > 3
      self.src         = line_src
      self.filename    = filename
      self.line_number = line_number
    end

    def self.format(line)
      line = line.split('|').map(&:strip)
      line[2] = line[2] ? line[2].to_i : 0
      line[3] = line[3] ? line[3].to_i : 0
      line
    end

    def score
      return 0 if num_asked == 0
      ((1.00 * num_right) / num_asked).round(1) - 0.1
    end

    def quiz!
      puts "#{question}?"
      STDOUT.flush
      ans = STDIN.gets.chomp
      if ans == answer
        puts "correct! Score is now #{score}"
        self.num_right = num_right + 1
      else
        puts "incorrect! Score is now #{score}. Correct answer is:"
        puts "  #{answer}"
      end
      self.num_asked = num_asked + 1
      write_results
    end

    def write_results
      output       = to_s
      before_line  = ''
      after_line   = ''
      File.open(filename, 'r') do |file|
        lines = file.each_line.to_a
        if line_number != 0
          before_line = lines[0..line_number-1]
        end
        if line_number != lines.length
          after_line  = lines[line_number+1..lines.length]
        end
      end
      file = File.open(filename, 'w')
      file.puts(before_line)
      file.puts(output)
      file.puts(after_line)
      file.close
    end

    def to_s
      str = src.split("|")[0..1].push(num_asked, num_right).join("|")
      "#{str}\n"
    end
  end
###############################################

operation  = ARGV[0]
filename   = ARGV[1]
operations = %w{ask drill}

death_by_usage unless operation && operations.index(operation) != nil
death_by_usage unless File.exists? filename
begin
  line_number = 0
  lines       = []
  File.open(filename, 'r') do | infile |
    while ( line = infile.gets )
      unless ignore line[0]
        lines.push( Line.new( line.chomp, filename, line_number ) )
      end
      line_number = line_number + 1
    end
  end

  lines.sort! { |a, b| a.score <=> b.score }
  lines.first.quiz!
end while operation == 'drill'
